<a href="https://colab.research.google.com/github/dipaksavitre-don/assiment-24/blob/main/assignmnet24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

classification_dataset = pd.read_csv(r"/content/diabetes.csv")
regresssion_dataset = pd.read_csv(r"/content/Chocolate_Sales.csv")

In [5]:
classification_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
regresssion_dataset.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69

In [7]:
# cleaning the classsification dataset
classification_dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
classification_dataset = classification_dataset.drop_duplicates()

In [9]:
classification_dataset.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [10]:

classification_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [11]:
mean_boxes = regresssion_dataset.loc[regresssion_dataset['Boxes_Shipped']>0,'Boxes_Shipped'].mean()
regresssion_dataset.loc[regresssion_dataset['Boxes_Shipped']<0,'Boxes_Shipped'] = int(mean_boxes)

In [12]:
regresssion_dataset['Amount'] = pd.to_numeric(regresssion_dataset['Amount'],errors='coerce')

In [13]:
amount_mean = regresssion_dataset.loc[regresssion_dataset['Amount'].notna(),'Amount'].mean()
regresssion_dataset['Amount'] = regresssion_dataset['Amount'].fillna(amount_mean)

In [14]:
# filling the null values in each columns
for i in classification_dataset.columns:
    if classification_dataset[i].isnull().sum()>0:
        if classification_dataset[i].dtype !='object':
            mean  = classification_dataset.loc[classification_dataset[i].notna(),i].mean()
            classification_dataset[i] = classification_dataset[i].fillna(mean)
        else:
            most_repeted = classification_dataset[i].value_counts().idxmax()
            classification_dataset[i] = classification_dataset[i].fillna(most_repeted)

In [15]:
# cheaking the dataset after cleanin
classification_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [16]:
classification_dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [17]:
# cleaning the regration dataset
regresssion_dataset.describe()

,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
count,55869.000000,55852.000000,55864.000000,55987.000000,55987.000000
mean,13.159966,5.926924,95.497180,142.443764,513.356196
std,6.379860,4.979255,66.373054,116.187609,365.315827
min,0.000000,2.040000,4.630000,1.000000,9.000000
25%,8.300000,2.950000,52.280000,69.000000,288.955000
50%,12.700000,3.280000,78.740000,116.000000,421.250000
75%,17.530000,4.895000,118.500000,179.000000,617.620000
max,36.900000,20.900000,798.222443,3554.000000,7920.490000

In [18]:
# Cleanin the incorrect values
columns_to_fix = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in columns_to_fix:
    mean_val = classification_dataset.loc[classification_dataset[col] > 0, col].mean()
    # Replace negative values with the mean
    classification_dataset.loc[classification_dataset[col] <= 0, col] = int(mean_val)

In [19]:
regresssion_dataset = regresssion_dataset.drop_duplicates()

In [20]:
regresssion_dataset.dtypes

Order_ID            object
Product             object
Country             object
Channel             object
Salesperson         object
Order_Date          object
Discount_Pct       float64
Price_per_Box      float64
Marketing_Spend    float64
Boxes_Shipped        int64
Amount             float64
dtype: object

In [21]:
regresssion_dataset.describe()

,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
count,55869.000000,55852.000000,55864.000000,55987.000000,55987.000000
mean,13.159966,5.926924,95.497180,142.443764,513.356196
std,6.379860,4.979255,66.373054,116.187609,365.315827
min,0.000000,2.040000,4.630000,1.000000,9.000000
25%,8.300000,2.950000,52.280000,69.000000,288.955000
50%,12.700000,3.280000,78.740000,116.000000,421.250000
75%,17.530000,4.895000,118.500000,179.000000,617.620000
max,36.900000,20.900000,798.222443,3554.000000,7920.490000

In [22]:
regresssion_dataset.isnull().sum()

Order_ID             0
Product              0
Country              0
Channel              0
Salesperson          0
Order_Date         120
Discount_Pct       118
Price_per_Box      135
Marketing_Spend    123
Boxes_Shipped        0
Amount               0
dtype: int64

In [23]:
# filling the null values in each columns
for i in regresssion_dataset.columns:
    if regresssion_dataset[i].isnull().sum()>0:
        if regresssion_dataset[i].dtype =='number':
            mean  = regresssion_dataset.loc[regresssion_dataset[i].notna(),i].mean()
            regresssion_dataset[i] = regresssion_dataset[i].fillna(mean)
        else:
            most_repeted = regresssion_dataset[i].value_counts().idxmax()
            regresssion_dataset[i] = regresssion_dataset[i].fillna(most_repeted)

In [24]:
classification_dataset.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [25]:
# spling the indipendent and targated features of each dataset
x_classification = classification_dataset[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI','Age']]
y_classfication = classification_dataset['Outcome']

In [26]:
x_classification.select_dtypes(include='number').columns

Index(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'Age'], dtype='object')

In [27]:
regresssion_dataset.columns

Index(['Order_ID', 'Product', 'Country', 'Channel', 'Salesperson',
       'Order_Date', 'Discount_Pct', 'Price_per_Box', 'Marketing_Spend',
       'Boxes_Shipped', 'Amount'],
      dtype='object')

In [28]:
x_regrassion = regresssion_dataset[['Product', 'Country', 'Channel',
       'Discount_Pct', 'Price_per_Box', 'Marketing_Spend',
       'Boxes_Shipped']]
y_regrassion = regresssion_dataset['Amount']

In [29]:
# converting all numerical columns into integer
xc_numcols = x_classification.select_dtypes(include='number').columns
x_classification[xc_numcols] = x_classification[xc_numcols].astype(int)

xr_numcols = x_regrassion.select_dtypes(include='number').columns
x_regrassion[xr_numcols] = x_regrassion[xr_numcols].astype(int)

/tmp/ipykernel_627/3417485739.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_classification[xc_numcols] = x_classification[xc_numcols].astype(int)
/tmp/ipykernel_627/3417485739.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_regrassion[xr_numcols] = x_regrassion[xr_numcols].astype(int)

In [30]:
# performing one hot encoding on categorical columns
xc_catcols = x_classification.select_dtypes(include='object').columns
x_classification = pd.get_dummies(x_classification,columns=xc_catcols)

In [31]:
xr_catcols = x_regrassion.select_dtypes(include='object').columns
x_regrassion = pd.get_dummies(x_regrassion,columns=xr_catcols)

In [32]:
# standard scaling the numerical columns
from sklearn.preprocessing import StandardScaler
xc_scaler = StandardScaler()
x_classification[xc_numcols] = xc_scaler.fit_transform(x_classification[xc_numcols])
xr_scaler = StandardScaler()
x_regrassion[xr_numcols] = xr_scaler.fit_transform(x_regrassion[xr_numcols])

In [33]:
# spliting dataset int traning and testing dataframes
from sklearn.model_selection import train_test_split

xc_train,xc_test,yc_train,yc_test = train_test_split(x_classification,y_classfication,random_state=42,shuffle=True,test_size=0.33)

In [34]:
xr_train,xr_test,yr_train,yr_test = train_test_split(x_regrassion,y_regrassion,random_state=42,shuffle=True,test_size=0.33)

In [35]:
"""Q2. (Classification Algorithms)
On the classification dataset, train and evaluate the following models:
Logistic Regression
Decision Tree Classifier
Support Vector Machine (SVM)
K-Nearest Neighbors (KNN)
Naive Bayes
For each model:
Train the model
Make predictions
Calculate Accuracy, Confusion Matrix, and Classification Report
Create a comparison table of all models’ performance."""

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()
logistic_model.fit(xc_train,yc_train)

LogisticRegression()

In [36]:
from sklearn.tree import DecisionTreeClassifier

decision_model = DecisionTreeClassifier()
decision_model.fit(xc_train,yc_train)

DecisionTreeClassifier()

In [37]:
from sklearn.neighbors import KNeighborsClassifier

K_model = KNeighborsClassifier(11)
K_model.fit(xc_train,yc_train)

KNeighborsClassifier(n_neighbors=11)

In [38]:
from sklearn.naive_bayes import GaussianNB
Navi_model = GaussianNB()
Navi_model.fit(xc_train,yc_train)

GaussianNB()

In [39]:
models = {
    'logistic_model':logistic_model,
    'decision-tree_model':decision_model,
    'KNN_model':K_model,
    'Navi-bias_model':Navi_model

}

In [40]:
# confusion matrix for each model
from sklearn.metrics import confusion_matrix
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Confusion matrix of:{i}\n{confusion_matrix(yc_test,y_pred)}")

Confusion matrix of:logistic_model
[[138  30]
 [ 38  48]]
Confusion matrix of:decision-tree_model
[[131  37]
 [ 43  43]]
Confusion matrix of:KNN_model
[[137  31]
 [ 30  56]]
Confusion matrix of:Navi-bias_model
[[138  30]
 [ 37  49]]

In [41]:
# Accuracy of each model
from sklearn.metrics import accuracy_score
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Accuracy for:{i}\n{accuracy_score(yc_test,y_pred)}")

Accuracy for:logistic_model
0.7322834645669292
Accuracy for:decision-tree_model
0.6850393700787402
Accuracy for:KNN_model
0.7598425196850394
Accuracy for:Navi-bias_model
0.7362204724409449

In [42]:
# classification report for each Model
from sklearn.metrics import classification_report
for i in models:
    x = models[i]
    y_pred = x.predict(xc_test)
    print(f"Classification Report for:{i}\n{classification_report(yc_test,y_pred)}")

Classification Report for:logistic_model
              precision    recall  f1-score   support

           0       0.78      0.82      0.80       168
           1       0.62      0.56      0.59        86

    accuracy                           0.73       254
   macro avg       0.70      0.69      0.69       254
weighted avg       0.73      0.73      0.73       254

Classification Report for:decision-tree_model
              precision    recall  f1-score   support

           0       0.75      0.78      0.77       168
           1       0.54      0.50      0.52        86

    accuracy                           0.69       254
   macro avg       0.65      0.64      0.64       254
weighted avg       0.68      0.69      0.68       254

Classification Report for:KNN_model
              precision    recall  f1-score   support

           0       0.82      0.82      0.82       168
           1       0.64      0.65      0.65        86

    accuracy                           0.76       254
   macro avg       0.73      0.73      0.73       254
weighted avg       0.76      0.76      0.76       254

Classification Report for:Navi-bias_model
              precision    recall  f1-score   support

           0       0.79      0.82      0.80       168
           1       0.62      0.57      0.59        86

    accuracy                           0.74       254
   macro avg       0.70      0.70      0.70       254
weighted avg       0.73      0.74      0.73       254

In [43]:
reports = {}

for name, model in models.items():
    y_pred = model.predict(xc_test)
    report = classification_report(yc_test, y_pred, output_dict=True)
    reports[name] = report['weighted avg']  # use weighted avg for overall comparison

# Convert to DataFrame
comparison_table = pd.DataFrame(reports).T
print(comparison_table)

                     precision    recall  f1-score  support
logistic_model        0.726970  0.732283  0.728867    254.0
decision-tree_model   0.679952  0.685039  0.682110    254.0
KNN_model             0.760538  0.759843  0.760178    254.0
Navi-bias_model       0.731582  0.736220  0.733317    254.0

In [44]:
"""Q3. (Regression Algorithms)
On the regression dataset, train and evaluate the following models:
Linear Regression
Decision Tree Regressor
Support Vector Regressor (SVR)
K-Nearest Neighbors Regressor
For each model:
Train the model
Make predictions
Calculate R2 Score
Create a comparison table showing which model performed best."""

'Q3. (Regression Algorithms)\nOn the regression dataset, train and evaluate the following models:\nLinear Regression\nDecision Tree Regressor\nSupport Vector Regressor (SVR)\nK-Nearest Neighbors Regressor\nFor each model:\nTrain the model\nMake predictions\nCalculate R2 Score\nCreate a comparison table showing which model performed best.'

In [45]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
linear_model.fit(xr_train,yr_train)

LinearRegression()

In [46]:
from sklearn.tree import DecisionTreeRegressor

dr_model = DecisionTreeRegressor()
dr_model.fit(xr_train,yr_train)

DecisionTreeRegressor()

In [47]:
from sklearn.svm import SVR

svr = SVR()
svr.fit(xr_train,yr_train)

SVR()

In [48]:
from sklearn.neighbors import KNeighborsRegressor

knr_model = KNeighborsRegressor()

knr_model.fit(xr_train,yr_train)

KNeighborsRegressor()

In [49]:
models2 = {
    'Decision Tree':dr_model,
    'Support Vector Machine':svr,
    'K nerest nabors':knr_model
}

In [50]:
from sklearn.metrics import r2_score
performance = {}

for name,model in models2.items():
    y_pre  = model.predict(xr_test)
    score = r2_score(yr_test,y_pre)
    print(f"R2 Score for model:{name} is:\n{score}")
    performance[name] = score
performance = pd.DataFrame([performance])

R2 Score for model:Decision Tree is:
0.770108412038133
R2 Score for model:Support Vector Machine is:
0.5235159410470445
R2 Score for model:K nerest nabors is:
0.791176877806942

In [51]:
# comparision table
performance

   Decision Tree  Support Vector Machine  K nerest nabors
0       0.770108                0.523516         0.791177

In [52]:
regration_cols = xr_train.columns
classification_cols = xc_train.columns

In [53]:
"""Q4. (Best Model Selection & Saving)
From Q2 and Q3:
Select the best classification model and best regression model based on
performance metrics.
Save both best models using joblib (also save scaler and columns if used)."""

# best classification model is KNN
# best regration model is also and K nerest nabors

# savin the models

import joblib as jb
jb.dump(K_model,'Knn-classification.pki')
jb.dump(knr_model,'Knn-regration.pki')
jb.dump(xc_scaler,'classification-scaler.pki')
jb.dump(xr_scaler,'regration-scaler.pki')
jb.dump(regration_cols,'regration-columns.pki')
jb.dump(classification_cols,'classification-columns.pki')

['classification-columns.pki']